### ISSUE TITLE
Code style?

### ISSUE THREAD

**Issue by granowski** [jwn57030/mediaplayer#1]
https://github.com/jwn57030/mediaplayer/blob/b582ccf4714f45d3bb4270cace173f0d23e37eed/api/media_player_api.c#L167

Normally from what I have seen in modern higher level languages we try to reduce the usage of chained if-elseif-else. There is a principal called early out, where one tries to return when a precondition fails then it reads sequentially and you don't have multiple branch blocks in a scope.

I can provide a sample in a bit...

**Comment by jwn57030** [comment]
I prefer style of only having one return point in the function.  If the function had more nested if/else blocks in it.  I could see this potentially being a good thing though.
