### ISSUE TITLE
Make all in test_app directory isn't working.

### ISSUE THREAD

**Issue by granowski** [jwn57030/mediaplayer#3]
I followed the readme instructions but the build didn't work.
I cd'd into test_app, then typed "make all" and got an error.
```
Makefile:5: /Users/granowski/CLionProjects/mediaplayer/test_app/media_player/common.mk: No such file or directory
Makefile:6: /Makefile: No such file or directory
make: *** No rule to make target `/Makefile'.  Stop.
```
I think it has something to do with the directory structure, as "test_app/media_player/common.mk" doesn't exist in the tree.

**Comment by granowski** [comment]
Extra info:
CLion uses bash, but the default shell in Mac OS X is zsh.
That might have something to do with it.

**Comment by jwn57030** [comment]
Build issues are fixed now

**Comment by jwn57030** [comment]
https://github.com/jwn57030/mediaplayer/commit/972bee7cc0ad689f87518f9e2e3ad85617862d11
